version: '3.9'

services:
  transcription-api:
    build: ./transcription-api
    ports:
      - 8000:8000
      
  translate:
    ports:
      - 5000:5000

  mongo:
    ports:
      - 27017:27017

  whishper-backend:
    build: ./backend
    ports:
      - 8080:8080
    
  whishper-frontend:
    build: 
      context: ./frontend
      args:
        PUBLIC_API_HOST: ${WHISHPER_PUBLIC_URL}
        PUBLIC_TRANSLATION_API_HOST: ""
        PUBLIC_INTERNAL_API_HOST: "http://nginx:80"