version: "3"

services:
  whisper-backend:
    build: .
    container_name: whishper-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ../uploads:/uploads
  whishper-mongo:
    image: mongo:4.4.18
    container_name: whishper-mongo
    restart: unless-stopped
    volumes:
      - ../db_data/db:/data/db
      - ../db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    ports:
      - 27017:27017
    command: mongod --logpath var/log/mongodb/mongod.log


   