name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create and push tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

  build-and-push:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update version in frontend package.json
        run: |
          VERSION_WITHOUT_V=$(echo "${{ github.event.inputs.version }}" | sed 's/^v//')
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION_WITHOUT_V\"/" frontend/package.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add frontend/package.json
          git commit -m "Update frontend version to $VERSION_WITHOUT_V" || echo "No changes to commit"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            thespartan94/whishper-frontend:${{ github.event.inputs.version }}
            thespartan94/whishper-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            thespartan94/whishper-backend:${{ github.event.inputs.version }}
            thespartan94/whishper-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Transcription API (GPU)
        uses: docker/build-push-action@v4
        with:
          context: ./transcription-api
          file: ./transcription-api/Dockerfile.gpu
          push: true
          tags: |
            thespartan94/whisper-transcription-api-gpu:${{ github.event.inputs.version }}
            thespartan94/whisper-transcription-api-gpu:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Transcription API (CPU)
        uses: docker/build-push-action@v4
        with:
          context: ./transcription-api
          file: ./transcription-api/Dockerfile.cpu
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            thespartan94/whisper-transcription-api-cpu:${{ github.event.inputs.version }}
            thespartan94/whisper-transcription-api-cpu:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max